export const ProductData = [
    {
        id:1,
        sku: 18644119330491312,
        title:"sphynx Tie Dye Grey T-shirt",
        quantity:1,
        describtion:'sphynx Tie Dye Grey T-shirt',
        availableSizes: ['X','L','XL','XXL'],
        price: 22,
        isFreeShipping:true,
    },
    {
        id:2,
        sku:55644119330491312,
        title:"BLue Tie Dye Grey T-shirt",
        quantity:1,
        describtion:'BLue Tie Dye Grey T-shirt',
        availableSizes: ['X','L'],
        price: 10,
        isFreeShipping:false,
    },
    {
        id:3,
        sku:15564779330491312,
        title:"Danger Tie Dye Grey T-shirt",
        quantity:1,
        describtion:'Danger Tie Dye Grey T-shirt',
        availableSizes: ['X','M','L','XL',],
        price: 18,
        isFreeShipping:true,
    },
    {
        id:4,
        sku:3524119330491312,
        title:"Man Tie Dye Grey T-shirt",
        quantity:1,
        describtion:'Man Tie Dye Grey T-shirt',
        availableSizes: ['X','L','XL','XXL'],
        price: 55,
        isFreeShipping:false,
    },
    {
        id:5,
        sku:90844119330491312,
        title:"Crazy Tie Dye Grey T-shirt",
        quantity:1,
        describtion:'Crazy Tie Dye Grey T-shirt',
        availableSizes: ['X','L','XL','XXL','XXL'],
        price: 87,
        isFreeShipping:true,
    },
    {
        id:6,
        sku:12344119330491312,
        title:"Tso 3D Dye Grey T-shirt",
        quantity:1,
        describtion:'Tso 3D Dye Grey T-shirt',
        availableSizes: ['X','XXL'],
        price: 23,
        isFreeShipping:false,
    },
    {
        id:7,
        sku:763892109330491312,
        title:"Tie Dye Grey T-shirt",
        quantity:1,
        describtion:'Tie Dye Grey T-shirt',
        availableSizes: ['S'],
        price: 49.5,
        isFreeShipping:true,
    },
    {
        id:8,
        sku:59874119330491312,
        title:"size Dye Grey T-shirt",
        quantity:1,
        describtion:'size Dye Grey T-shirt',
        availableSizes: ['X'],
        price: 11,
        isFreeShipping:false,
    },
    {
        id:9,
        sku:181234119330491312,
        title:"Tso sphynx Tie Dye",
        quantity:1,
        describtion:'Tso sphynx Tie Dye',
        availableSizes: ['L','XL'],
        price: 19,
        isFreeShipping:true,
    },
]